### ISSUE TITLE
Another bug with the Alchemy call function

### ISSUE THREAD

**Issue by sirmarcis** [opinionated/OpinionatedNLPAnalysis#8]
Has to do with Courtney's code, which I still don't really get..

It gives me an index out of bounds exception:
"on article[ 5 ] article name: OilExportsandRenewableEnergy
beginning Alchemy call
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main()
  File "main.py", line 42, in main
    curr_alchemy_data, can_continue_p = perform_article_theme_extraction(json_file_data, json_filename, alchemy_language)
  File "/home/anders/Documents/RCOS/OpinionatedNLPAnalysis/article_data_extraction.py", line 70, in perform_article_theme_extraction
    sentence_data, success_p = call_alchemy(sentence[0], alchemy_language)
  File "/home/anders/Documents/RCOS/OpinionatedNLPAnalysis/article_data_extraction.py", line 55, in call_alchemy
    d['keywords'][i]['emotions'] = emotions[i+len(d['entities'])]['emotions']
IndexError: list index out of range
"

**Comment by sirmarcis** [comment]
This seems to be a bug relating to assigning keywords their emotion hash's, and the latter not being present in the returned data from Alchemy...?

**Comment by sirmarcis** [comment]
Found issue.  We are assigning the wrong emotions to keywords and entities in some cases.  This means that we have to run all previously finished articles again...
